/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_noweaj_android_pupildetection_main_MainActivity */

#ifndef _Included_com_noweaj_android_pupildetection_main_MainActivity
#define _Included_com_noweaj_android_pupildetection_main_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_noweaj_android_pupildetection_main_MainActivity_CAMERA_PERMISSION_REQUEST_CODE
#define com_noweaj_android_pupildetection_main_MainActivity_CAMERA_PERMISSION_REQUEST_CODE 200L
/*
 * Class:     com_noweaj_android_pupildetection_main_MainActivity
 * Method:    ConvertRGBtoGray
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_noweaj_android_pupildetection_main_MainActivity_ConvertRGBtoGray
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
