/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_noweaj_android_pupildetection_main_MainPresenter */

#ifndef _Included_com_noweaj_android_pupildetection_main_MainPresenter
#define _Included_com_noweaj_android_pupildetection_main_MainPresenter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_noweaj_android_pupildetection_main_MainPresenter
 * Method:    ConvertRGBtoGray
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_noweaj_android_pupildetection_main_MainPresenter_ConvertRGBtoGray
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_noweaj_android_pupildetection_main_MainPresenter
 * Method:    LoadCascade
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_noweaj_android_pupildetection_main_MainPresenter_LoadCascade
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
